### PR TITLE
Refactor and update Akismet addon

### PR DESCRIPTION
**Pull request by sswebster**
## Description
This PR updates and refactors the Akismet addon in preparation for its release. Specifically it:

- Refactors several methods for more simplicity
- Breaks out the fields filter and plugin settings into their own classes
- Adds our unit testing framework and includes several tests
- Adds the menu icon
- Adds our namespace

This would resolve https://github.com/gravityforms/backlog/issues/1359. 

https://github.com/gravityforms/backlog/issues/1392 will be merged into this branch unless this is approved and merged into master first.

## Testing Instructions
- This is mostly a refactor so there isn't anything new to test, but we should make sure everythings still works
- Install and activate Akismet and this version of the Akismet Addon
- Go to Forms->Settings and toggle Akismet on
- Use a form with all fields or create a form with at least a name, email, url, and paragraph field
- Go to the form's settings and go to Akismet
- Make sure that default merge tags are populated
- You won't be able to add new merge tags for author, url, or email, but that will be fixed in Jeremy's branch when these are replaced with field maps
- Save the settings
- Preview and submit the form and make sure it goes through
- Preview again and submit the form with "viagra-test-123" in the name field. Make sure it's marked as spam

## Checklist
- [x] I've tested my code locally to ensure it functions as intended.
- [x]  I've checked the error log to ensure my code doesn't throw any errors.
- [ ]  I've added a changelog entry (if necessary).
- [x]  My code passes all Unit Tests.
- [ ]  My code passes all Acceptance Tests.
- [x]  My code follows the WordPress code style.
- [x]  My code follows the accessibility standards.
- [x]  My code follows the inline documentation standards.
- [x]  This PR has a related issue.
- [x]  This PR has a related test.

### CODE REVIEW

**Comment by sswebster** [comment]
@jmichaelward I requested other reviews since you wrote a big chunk of this and we've looked at it extensively together, but wanted to give you the chance to sign off again as well

**Review by michelle-bauer — COMMENTED** [review]
Functionality wise this works as expected without error.

I have some design related observations for the form settings page:

1. Should the fields be hidden when the spam check button is not enabled (like how Partial Entries works)?

2. The focus state for the Content field looks different than the other fields.
Akismet 1Akismet 2

3. The checkbox and merge tag buttons look off in RTL.
Akismet 3

**Comment by jmichaelward** [comment]
@michelle-bauer Thanks for the review. I think we want to leave all of the UI-based feedback for #3, since that work is all associated with updating the UI as part of gravityforms/backlog#1392. Essentially, the result of Sam's work should look and behave the same as the master branch for this add-on, since it's strictly a refactor and introduction of the unit test suite.

That said, I am interested in why some of these elements aren't displaying properly, and expect these issues will persist in the other PR. There is no custom stylesheet in this add-on - everything comes from core - so we may have some other underlying issues in the settings API styles.

**Review by jmichaelward — APPROVED** [review]
@sswebster I think this looks great. I like the extra steps you took to invert logic in some of the methods to return early and reduce the amount of nesting. 

As you mentioned during today's standup, #3 will fix the issues with unit tests, and I think we'll have a bit more light refactoring there, too (e.g., removing "_Enhancements" from the main add-on class), but this PR satisfies the work of your issue and I think this should be good to merge along with another dev's approval since we worked on a decent portion of this together.

**Comment by sswebster** [comment]
Thanks @michelle-bauer! As Jeremy indicated, the structure of these fields will be changing completely in the other Akismet PR, so this shouldn't be fixed here. This is just for the refactor and new tests.

**Review by michelle-bauer — APPROVED** [review]
This is the first time I've actually tested this add-on so obviously I wanted to report the issues I noted.  If that's the case, then I approve!  👍🏻

**Review by richardW8k — APPROVED** [review]

**Pull request merged**
